# Generated by Django 3.1.12 on 2024-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='user_prompt',
            field=models.TextField(default='Default prompt'),
            preserve_default=False,
        ),
    ]
